### ISSUE TITLE
[Bug]: OpenVINO Server does not override the default max_context_length=512 with the value specified in the model.xml file

### ISSUE THREAD

**Issue by fedecompa** [openvinotoolkit/model_server#2923]
### OpenVINO Version

 2024.5

### Operating System

Windows 11

### Device used for inference

GPU

### Framework

None

### Model used

BAAI/bge-m3

### Issue description

Openvino Server does not override the default max_context_length=512 with the one contained  in the model.xml file 

### Step-by-step reproduction

Convert the embedding model to the OpenVINO IR format using the OpenVINO Toolkit and serve it with the openvino/model_server:latest-gpu Docker image.

When calling the http://localhost:8001/v3/embeddings API, the server throws the following error, even though the model has a max_position_embeddings value of 8194:

calculator_graph.cc:853] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "EmbeddingsCalculator" failed: Input length 617 longer than allowed 512

### Relevant log output

```shell
calculator_graph.cc:853] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "EmbeddingsCalculator" failed: Input length 617 longer than allowed 512
```

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by dtrawins** [comment]
@fedecompa The windows version of the server was not retrieving correctly the information from the model about the context. It is now corrected on the main branch. Note that generative endpoint on windows server are now under development and testing. Production ready windows version of the server will be published in the coming release.

**Comment by fedecompa** [comment]
@dtrawins thanks for the reply, so to test it I need to wait for the openvino/model_server:2024.6-gpu right?

**Comment by dtrawins** [comment]
@fedecompa for the docker image and linux binary package, you can use the public image 2024.5. Just follow the demo from https://github.com/openvinotoolkit/model_server/tree/releases/2024/5/demos/rerank 
Windows native binary package is planned to be published in 2025.0 in February.
It is possible, though, to build the windows package from sources.

**Comment by fedecompa** [comment]
@dtrawins I'm using the 2024.5-gpu docker image but the bug is still there: 

{"error": "Mediapipe execution failed. MP status - INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "EmbeddingsCalculator" failed: Input length 538 longer than allowed 512"}

**Comment by dtrawins** [comment]
@fedecompa please switch to new version 2025.0. This problem has been fixed in the last release.

**Comment by dtrawins** [comment]
@fedecompa The error might indicate that you are trying to deploy the model on GPU but the GPU is not functional for some reasons. It could be that you have the image without gpu drivers (try the label 2025.0-gpu) or  you are not using --device /dev/dri parameter and --group-add .

**Comment by fedecompa** [comment]
@dtrawins no because I'm using the same docker-compose and the same models, but with the image openvino/model_server:2024.5-gpu it works and with the image openvino/model_server:2025.0-gpu it doesn't work and throws the above error.

**Comment by dtrawins** [comment]
@fedecompa That is very strange. Can you share the logs and output of docker inspect command for the running container? 
Also what is the host OS and platform and GPU model?
 Generally it is recommended to use for version 2025.0 the models exported also with OV2025.0 and the requirements from https://raw.githubusercontent.com/openvinotoolkit/model_server/refs/heads/releases/2025/0/demos/common/export_models/requirements.txt. The error message suggest however the problem is that GPU is not working inside the container. Could it that you have some very old integrated GPU which is not supported in the latest drivers https://github.com/intel/compute-runtime/releases/tag/24.52.32224.5 which are in the latest docker image?

**Comment by dtrawins** [comment]
@fedecompa if you are using windows host, you don't need docker containers. You could just use windows native package from 2025.0 release. 
It is recommended to reexport the models but this is not related to your error.
Your windows driver does support your GPU but most likely the driver in the latest public docker image doesn't. If you need to use docker container, you might need to build the image with older driver version or with Ubuntu22 base image.

**Comment by fedecompa** [comment]
@dtrawins " but most likely the driver in the latest public docker image doesn't. "

Then this means that there has been a regression in the image model_server:2025.0-gpu, because with the image model_server:2024.5-gpu it works.

**Comment by dtrawins** [comment]
@fedecompa the public image includes the drivers supporting newer platforms which unfortunately drop support for the older. But you can still enable version 2025.0 to work on the older machines:
Option1 - build the image with older version
```
git clone -b releases/2025/0 https://github.com/openvinotoolkit/model_server
cd model_server
make release_image INSTALL_DRIVER_VERSION=24.26.30049
```

Option2 - just all the older drivers to the public image. It will be quicker.
Build the image using the Dockerfile below:
```
FROM openvino/model_server:2025.0
USER 0
ENV INSTALL_DRIVER_VERSION=24.26.30049
RUN curl -L https://raw.githubusercontent.com/openvinotoolkit/model_server/refs/heads/releases/2025/0/install_ubuntu_gpu_drivers.sh -o /tmp/install_gpu_drivers.sh ; \
    chmod 755 /tmp/install_gpu_drivers.sh ; \
    /tmp/install_gpu_drivers.sh
USER ovms
ENTRYPOINT ["/ovms/bin/ovms"]
```

**Comment by fedecompa** [comment]
@dtrawins I will try thanks, but in the list of supported GPUs for the latest drivers by Intel there is the Intel® UHD Graphics, so one expect it to work.

**Comment by fedecompa** [comment]
@dtrawins option2 works thanks

**Comment by fedecompa** [comment]
@dtrawins The test for the bug in the issue also seems fine, but now I get this exception:

 400 - {"error":"Mediapipe execution failed. MP status - INTERNAL: CalculatorGraph::Run() failed: \nCalculator::Process() for node \"EmbeddingsCalculator\" failed: ; RET_CHECK failure (src/embeddings/embeddings_calculator.cc:257) false"}

**Comment by dtrawins** [comment]
@fedecompa Could you include a complete log from the server? If you start the server with `--log_level DEBUG` there should be more clues related to the root cause. 
Also what model did you use?  Was the model exported like described in https://github.com/openvinotoolkit/model_server/tree/releases/2025/0/demos/embeddings
Did it fail with some specific request length or batch size?

**Comment by fedecompa** [comment]
@dtrawins yes the model is in "BAAI/bge-m3" and is the OV format. It fail when I do a call to the embedding API. This is the complete log with debug. But it looks pretty strange, because the memory required is available. 

2025-02-20 15:10:51 [2025-02-20 14:10:51.617][234][serving][error][modelinstance.cpp:1404] Async caught an exception Internal inference error: Exception from src/inference/src/cpp/infer_request.cpp:245:
2025-02-20 15:10:51 Check '!exceed_available_mem_size' failed at src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp:159:
2025-02-20 15:10:51 [GPU] Exceeded max size of memory allocation: Required 155730960 bytes, already occupied : 10359322718 bytes, but available memory size is 10432905216 bytes
2025-02-20 15:10:51 
2025-02-20 15:10:51 
2025-02-20 15:10:51 [2025-02-20 14:10:51.617][234][embeddings_calculator][debug][embeddings_calculator.cc:255] Caught exception from session infer(): Internal inference error
2025-02-20 15:10:51 I20250220 14:10:51.617175   234 modelapiovmsadapter.cc:130] Error encountred in OVMSCalculator:Internal inference error code: 77
2025-02-20 15:10:51 I20250220 14:10:51.617878   234 embeddings_calculator.cc:256] Internal inference error
2025-02-20 15:10:51 [2025-02-20 14:10:51.619][65][serving][debug][mediapipegraphexecutor.hpp:178] graph wait until idle INTERNAL: CalculatorGraph::Run() failed: 
2025-02-20 15:10:51 Calculator::Process() for node "EmbeddingsCalculator" failed: ; RET_CHECK failure (src/embeddings/embeddings_calculator.cc:257) false
2025-02-20 15:10:51 [2025-02-20 14:10:51.619][65][serving][debug][http_server.cpp:244] Processing HTTP/REST request failed: POST /v3/embeddings. Reason: Mediapipe execution failed. MP status - INTERNAL: CalculatorGraph::Run() failed: 
2025-02-20 15:10:51 Calculator::Process() for node "EmbeddingsCalculator" failed: ; RET_CHECK failure (src/embeddings/embeddings_calculator.cc:257) false
2025-02-20 15:10:51 WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
2025-02-20 15:10:51 E0000 00:00:1740060651.618390      65 calculator_graph.cc:898] INTERNAL: CalculatorGraph::Run() failed: 
2025-02-20 15:10:51 Calculator::Process() for node "EmbeddingsCalculator" failed: ; RET_CHECK failure (src/embeddings/embeddings_calculator.cc:257) false
2025-02-20 15:10:51 I20250220 14:10:51.619496    65 modelapiovmsadapter.cc:70] OVMSAdapter destr
2025-02-20 15:10:51 I20250220 14:10:51.619552    65 modelapiovmsadapter.cc:70] OVMSAdapter destr

**Comment by fedecompa** [comment]
@dtrawins it is the batchingStrategy, since embedding one chunk at a time it doesn't throws the error.

**Comment by dtrawins** [comment]
@fedecompa apparently there is insufficient GPU memory for the allocation with the bigger batch size. The allocation might be quite high with long inputs and big batches. You have also high memory consumption probably from the load other than embedding model.
Be aware that WSL is assigning half of the host RAM so the linux OS might see less than the host. Also iGPU is using the OS memory but only half of it. 
I see the following options:
- reduce RAM usage from other apps
- use lower precision in the model via quantization Int8 or even Int4
- use lower batch size

**Comment by fedecompa** [comment]
@dtrawins yes I sounds like that, but the error log is nonsense, because "available" > "Required" : 

 "Required 155730960 bytes, already occupied : 10359322718 bytes, but available memory size is 10432905216 bytes"

**Comment by dtrawins** [comment]
@fedecompa Perhaps this log is not fully intuitive but here the available memory refers to the host or accelerator installed memory. Out of such "available" memory there is reported occupied volume. The difference would represent free memory which is less than the required allocation.
As a reference, here is the code which defines this behavior https://github.com/openvinotoolkit/openvino/blob/69d4b3b232065fb416c570ab59d8ffcf29f690b0/src/plugins/intel_gpu/src/runtime/engine.cpp#L83
https://github.com/openvinotoolkit/openvino/blob/69d4b3b232065fb416c570ab59d8ffcf29f690b0/src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp#L164
